In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("DataProjects 1.csv")

In [3]:
df

,_id,userId,projectName,description,totalHoursWorked,techUsed,performance,isApproved,approvedBy,Domain
0,66123929c478ba97b06a87b5,6612382ec478ba97b06a6c5d,Whole face System,Home something somebody stuff team feeling. De...,106,Power BI,good,True,David Stephens,Data
1,66123929c478ba97b06a87b6,6612382ec478ba97b06a6c5d,Coach around System,Another still forward early class address ever...,100,Python,good,True,Linda Dunn,Data
2,66123929c478ba97b06a87b7,6612382ec478ba97b06a6c5e,Card expert System,Boy water real adult cold and. Central word we...,144,AWS Lambda,good,True,Lynn Schaefer,Full Stack
3,66123929c478ba97b06a87b8,6612382ec478ba97b06a6c5e,Next include System,Whom herself mean popular career list factor. ...,73,Javascript,good,True,Brittany Flores,Full Stack
4,66123929c478ba97b06a87b9,6612382ec478ba97b06a6c5f,Up election System,Night course eight vote production field campa...,142,Alteryx,average,True,Brooke Hamilton,Full Stack
...,...,...,...,...,...,...,...,...,...,...
1995,6612396ec478ba97b06a8f80,6612386ac478ba97b06a7042,Imagine mission System,Responsibility blue despite. Remember try word...,75,React,good,True,Maria Jimenez,Full Stack
1996,6612396ec478ba97b06a8f81,6612386ac478ba97b06a7043,Do minute System,Exist direction clear director ago. Care will ...,133,AWS Lambda,average,True,Christy Simmons,Data
1997,6612396ec478ba97b06a8f82,6612386ac478ba97b06a7043,Many decide System,Southern establish treat friend. Black either ...,146,AWS Lambda,excellent,True,Donald Bennett,Full Stack
1998,6612396ec478ba97b06a8f83,6612386ac478ba97b06a7044,Detail gas System,Teacher operation pattern month care step term...,135,React,excellent,True,Jacqueline Rose,Data
1999,6612396ec478ba97b06a8f84,6612386ac478ba97b06a7044,Much spring System,One their PM employee factor fill fly. Confere...,64,Python,average,True,Jasmine Ellison,Data

In [4]:
project_names = [
    "CodeCrafter", "PixelForge", "WebWarp", "AppArchitect", "StackSavvy",
    "CodeCanvas", "DevDynamo", "ByteBridge", "PixelPulse", "TechTrek",
    "AppAlchemy", "WebWeave", "CodeCraftsman", "StackStream", "DevForge",
    "ByteBlast", "PixelPioneer", "TechTerra", "WebWizardry", "CodeCompass",
    "DataForge", "StreamSculpt", "DataMason", "PipelinePro", "DataDynamo",
    "StreamSmith", "DataFlowX", "ETLGenius", "DataPulse", "FlowForge",
    "DataCraftsman", "PipelinePioneer", "DataSculptor", "StreamSavvy",
    "DataWarp", "FlowFlex", "ETLArchitect", "DataForge", "StreamBuilder",
    "DataPulse", "Insightify", "AnalyticaPro", "DataVista", "TrendTrack",
    "AnalyzeRight", "DataScope", "InsightForge", "AnalyticsPulse", "TrendTrek",
    "DataNexus", "InsightGenius", "AnalyzeAll", "DataHorizon", "TrendSpotter",
    "InsightSavvy", "AnalytixPro", "DataWave", "TrendTerra", "InsightStream",
    "AnalyzeWise", "DataStack", "DataDriven", "FullDataForge", "CodeCraftsmanX",
    "StackStream", "DataDevForge", "FullStackInsight", "ByteBridgeX",
    "DataSavvyStack", "StackForge", "DataCraftsmanX", "FullTechTrek", "StreamStack",
    "DataByteForge", "StackSculptor", "InsightStack", "FullAnalytica", "DataTrekker",
    "CodeCraftsmanInsight", "AnalyzeByte", "StackScope", "InsightForgeX",
    "FullTrendTrack", "DataCraftsmanInsight", "AnalyzeStack", "StackSavvyInsight",
    "InsightStreamX", "FullDataNexus", "AnalyzeStream", "StackSpotter", "DataStacker",
    "FullDataInsight", "CodeCraftsmanData", "InsightBuilder", "DataForgeX",
    "FullStreamSculpt", "ByteBridgeData", "DataSavvyInsight", "FullInsightForge",
    "StackCraftsmanData"
]

In [5]:
import random

In [6]:
random.shuffle(project_names)

In [7]:
df['projectName'] = random.choices(project_names, k=len(df))

In [8]:
columns_drop = ['_id' , 'description' , 'isApproved' , 'approvedBy']

In [9]:
df = df.drop(columns=columns_drop , axis=1)

In [10]:
df

,userId,projectName,totalHoursWorked,techUsed,performance,Domain
0,6612382ec478ba97b06a6c5d,TechTerra,106,Power BI,good,Data
1,6612382ec478ba97b06a6c5d,StackForge,100,Python,good,Data
2,6612382ec478ba97b06a6c5e,InsightStack,144,AWS Lambda,good,Full Stack
3,6612382ec478ba97b06a6c5e,TrendTerra,73,Javascript,good,Full Stack
4,6612382ec478ba97b06a6c5f,DataCraftsmanInsight,142,Alteryx,average,Full Stack
...,...,...,...,...,...,...
1995,6612386ac478ba97b06a7042,TrendTrack,75,React,good,Full Stack
1996,6612386ac478ba97b06a7043,InsightStream,133,AWS Lambda,average,Data
1997,6612386ac478ba97b06a7043,DataStacker,146,AWS Lambda,excellent,Full Stack
1998,6612386ac478ba97b06a7044,StreamStack,135,React,excellent,Data
1999,6612386ac478ba97b06a7044,StackSavvyInsight,64,Python,average,Data

In [13]:
df.to_csv('updatedProjects.csv')